# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ClipTool.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(154, 596)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.centralwidget.setFont(font)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_screen = QtWidgets.QVBoxLayout()
        self.verticalLayout_screen.setObjectName("verticalLayout_screen")
        self.plainTextEdit_history = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_history.setObjectName("plainTextEdit_history")
        self.verticalLayout_screen.addWidget(self.plainTextEdit_history)
        self.plainTextEdit_paste = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.plainTextEdit_paste.setObjectName("plainTextEdit_paste")
        self.verticalLayout_screen.addWidget(self.plainTextEdit_paste)
        self.lineEdit_cmd = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_cmd.setObjectName("lineEdit_cmd")
        self.verticalLayout_screen.addWidget(self.lineEdit_cmd)
        self.verticalLayout_screen.setStretch(0, 5)
        self.verticalLayout_screen.setStretch(1, 1)
        self.verticalLayout_screen.setStretch(2, 1)
        self.horizontalLayout.addLayout(self.verticalLayout_screen)
        self.verticalLayout_patterns = QtWidgets.QVBoxLayout()
        self.verticalLayout_patterns.setObjectName("verticalLayout_patterns")
        self.horizontalLayout.addLayout(self.verticalLayout_patterns)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 154, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
